name: mighty_delivery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  intl: ^0.17.0
  html: ^0.15.0
  http: ^0.13.4
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

  nb_utils: ^4.4.14
  url_launcher: ^6.0.20
  date_time_picker: ^2.1.0
  animated_bottom_navigation_bar: ^0.3.2
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.0
  syncfusion_flutter_signaturepad: ^19.4.56
  screenshot: ^1.2.3
  flutter_google_places: ^0.3.0
  lottie: ^1.2.2
  timeline_tile: ^2.0.0
  flutter_stripe: ^2.3.0
  razorpay_flutter: ^1.2.9
  flutterwave_standard: ^1.0.3
  flutter_paystack: ^1.0.5+1

  # MAP
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.2
  flutter_polyline_points: ^1.0.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.3.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/flag/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
