name: mighty_delivery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  intl: ^0.17.0
  html: ^0.15.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

  nb_utils: ^4.4.12
  google_fonts: ^2.2.0
  bubble_bottom_bar: ^2.0.0
  url_launcher: ^6.0.18
  date_time_picker: ^2.1.0
  animated_bottom_navigation_bar: ^0.3.2
  image_picker: ^0.8.4+6
  cached_network_image: ^3.2.0
  syncfusion_flutter_signaturepad: ^19.4.48
  screenshot: ^1.2.3
  flutter_google_places: ^0.3.0
  lottie: ^1.2.1
  timeline_tile: ^2.0.0
  animations: ^2.0.2
  google_places_for_flutter: ^1.0.1
  geolocator: ^8.2.0
  address_search_field: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  address_search_field: ^4.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
