name: mighty_delivery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # CONNECTIVITY
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  intl: ^0.18.1
  html: ^0.15.4
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  flutter_vector_icons: ^2.0.0


  # STATE MANAGEMENT
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0

  # Base
  nb_utils: ^6.0.6
  google_fonts: ^6.1.0
  animated_bottom_navigation_bar: ^1.3.0
  animated_notch_bottom_bar: ^1.0.0

  # TOOLS
  cupertino_icons: ^1.0.6
  lottie: ^2.7.0
  timeline_tile: ^2.0.0
  country_code_picker: ^3.0.0

  # Dotted Line
  dotted_line: ^3.2.2

  # Payment gateway
  flutter_stripe: ^9.5.0+1
  razorpay_flutter: ^1.3.5
  flutterwave_standard: ^1.0.8
  paytm: ^3.0.1
  flutter_paystack: ^1.0.7
  flutter_braintree: ^3.0.0
#  mercado_pago_mobile_checkout: ^0.2.0-dev.3
  flutter_paytabs_bridge: ^2.6.3
  my_fatoorah: ^3.3.0

  # IMAGES
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  cached_network_image: ^3.3.0
  syncfusion_flutter_signaturepad: ^23.2.4
  screenshot: ^2.1.0
  date_time_picker: ^2.1.0

  # MAP
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  maps_launcher: ^2.2.0
  google_maps_place_picker_mb: ^3.1.2

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.0.4

  #OTP TEXTFIELD
  otp_text_field: ^1.1.3

  #FIREBASE
  firebase_crashlytics: ^3.4.4
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.1
  firebase_database: ^10.3.4
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^4.13.1

  # DOWNLOAD INVOICE PDF
  pdf: ^3.10.6
  path_provider: ^2.1.1
  open_file: ^3.3.2
  printing: ^5.11.1

  # READ MORE LESS
  readmore: ^2.2.0

  # SOCIAL LOGIN
  google_sign_in: ^6.1.4
  the_apple_sign_in: ^1.1.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

dependency_overrides:
  intl: ^0.18.0
  http: ^0.13.5
  connectivity_plus: ^3.0.3
  freezed_annotation: ^2.2.0
  cloud_firestore: ^4.8.1

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/flag/
    - assets/icon/

