name: mighty_delivery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # CONNECTIVITY
  url_launcher: ^6.1.6
  package_info_plus: ^1.4.2
  intl: ^0.17.0
  html: ^0.15.0
  http: ^0.13.5
  connectivity_plus: ^2.3.9

  # STATE MANAGEMENT
  mobx: ^2.1.0
  flutter_mobx: ^2.0.6+4

  # Base
  nb_utils: ^4.6.22
  google_fonts: ^3.0.1
  animated_bottom_navigation_bar: ^1.1.0

  # TOOLS
  cupertino_icons: ^1.0.5
  lottie: ^1.4.3
  timeline_tile: ^2.0.0
  country_code_picker: ^2.0.2

  # Dotted Line
  dotted_line: ^3.1.0

  # Payment gateway
  flutter_stripe: ^3.0.0
  razorpay_flutter: ^1.3.0
  flutterwave_standard: ^1.0.6
  paytm: ^3.0.1
  flutter_paystack: ^1.0.6
  flutter_braintree: ^2.3.1
  mercado_pago_mobile_checkout: ^0.2.0-dev.3
  flutter_paytabs_bridge: ^2.3.0
  my_fatoorah: ^3.1.0

  # IMAGES
  image_picker: ^0.8.6
  file_picker: ^4.5.1
  cached_network_image: ^3.2.2
  syncfusion_flutter_signaturepad: ^20.3.48
  screenshot: ^1.2.3
  date_time_picker: ^2.1.0

  # MAP
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.4.1

  #OTP TEXTFIELD
  otp_text_field: ^1.1.3

  #FIREBASE
  firebase_crashlytics: ^2.8.13
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  firebase_storage: ^10.3.11
  firebase_database: ^9.1.7
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^3.5.1

  # DOWNLOAD INVOICE PDF
  pdf: ^3.8.3
  path_provider: ^2.0.11
  open_file: ^3.2.1
  printing: ^5.9.3

  # READ MORE LESS
  readmore: ^2.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+3

dependency_overrides:
  freezed_annotation: ^2.1.0

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/flag/

